"""Fix foreign key issue

Revision ID: 335afea25d7b
Revises: 55050244904f
Create Date: 2024-10-09 13:30:48.343862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '335afea25d7b'
down_revision: Union[str, None] = '55050244904f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers1')
    op.add_column('question_answers', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('question_answers', 'answer',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('question_answers_user_id_fkey', 'question_answers', type_='foreignkey')
    op.create_foreign_key(None, 'question_answers', 'users', ['email'], ['email'])
    op.drop_column('question_answers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_answers', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question_answers', type_='foreignkey')
    op.create_foreign_key('question_answers_user_id_fkey', 'question_answers', 'users', ['user_id'], ['email'])
    op.alter_column('question_answers', 'answer',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('question_answers', 'email')
    op.create_table('question_answers1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='question_answers1_email_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_answers1_pkey')
    )
    # ### end Alembic commands ###
